# Build speed aur stability ke liye standard memory
org.gradle.jvmargs=-Xmx1536M -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError

android.useAndroidX=true
android.enableJetifier=true

# Inhe TRUE rakhne se build fast aur stable hoti hai
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.caching=true

# Kotlin settings ko standard par rakhein
kotlin.code.style=official
